[build]
target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-gnu]
linker = ".toolchains/mingw64/bin/x86_64-w64-mingw32-gcc.exe"
ar     = ".toolchains/mingw64/bin/x86_64-w64-mingw32-gcc-ar.exe"
